modLoader="javafml"
loaderVersion="[2,)"
license="CC0-1.0"

[[mods]]
modId="multiloader-template"
version="${file.jarVersion}"
displayName="MultiLoader Template"
description='''
This is an example description! Tell everyone what your mod is about!
'''

[[dependencies.multiloader-template]]
modId="minecraft"
type="required"
versionRange="[1.21,)"
ordering="NONE"
side="BOTH"
